### ISSUE TITLE
Why use a let here?

### ISSUE THREAD

**Issue by joostf** [TessaViergever/fix-the-flow-interactive-website-sprint-5#8]
https://github.com/TessaViergever/fix-the-flow-interactive-website-sprint-5/blob/a481ed2ea5c9f6f50367db10739fdc0b6fb08ede/scripts/index.js#L4

**Comment by joostf** [comment]
And use  cameCase for variable names

**Comment by TessaViergever** [comment]
Omdat het op deze manier door Justus uitgelegd is en ik JS niet goed genoeg ken om iets anders te gebruiken.
